name             'customization'
maintainer       'Christoffer Reijer'
maintainer_email 'ephracis at gmail'
license          'GPLv3'
description      'Customizes the node with tools and configuration tweaks'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
issues_url       'http://github.com/simplare-cookbooks/cutomization/issues'
source_url       'http://github.com/simplare-cookbooks/cutomization'
depends          'oh-my-zsh'
depends          'yum-epel'
